# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_resources/rubrique.ui'
#
# Created: Fri May 20 06:52:50 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1219, 600)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/publishstamp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setEnabled(True)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(3)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.leftpane = QtGui.QFrame(self.splitter)
        self.leftpane.setMinimumSize(QtCore.QSize(150, 0))
        self.leftpane.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leftpane.setFrameShape(QtGui.QFrame.NoFrame)
        self.leftpane.setFrameShadow(QtGui.QFrame.Raised)
        self.leftpane.setLineWidth(0)
        self.leftpane.setObjectName(_fromUtf8("leftpane"))
        self.verticalLayout = QtGui.QVBoxLayout(self.leftpane)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.blogrel = QtGui.QTabWidget(self.leftpane)
        self.blogrel.setTabPosition(QtGui.QTabWidget.North)
        self.blogrel.setTabShape(QtGui.QTabWidget.Rounded)
        self.blogrel.setObjectName(_fromUtf8("blogrel"))
        self.blogposts = QtGui.QWidget()
        self.blogposts.setObjectName(_fromUtf8("blogposts"))
        self.postTree = QtGui.QTreeWidget(self.blogposts)
        self.postTree.setGeometry(QtCore.QRect(0, 0, 243, 203))
        self.postTree.setObjectName(_fromUtf8("postTree"))
        self.postTree.headerItem().setText(0, _fromUtf8("Posts"))
        self.postTree.header().setVisible(False)
        self.blogrel.addTab(self.blogposts, _fromUtf8(""))
        self.localposts = QtGui.QWidget()
        self.localposts.setObjectName(_fromUtf8("localposts"))
        self.blogrel.addTab(self.localposts, _fromUtf8(""))
        self.verticalLayout.addWidget(self.blogrel)
        self.toolBox = QtGui.QToolBox(self.leftpane)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.toolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Raised)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.tb_categories = QtGui.QWidget()
        self.tb_categories.setGeometry(QtCore.QRect(0, 0, 205, 126))
        self.tb_categories.setObjectName(_fromUtf8("tb_categories"))
        self.widget = QtGui.QWidget(self.tb_categories)
        self.widget.setGeometry(QtCore.QRect(-8, -1, 261, 221))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.categoriestree = QtGui.QTreeWidget(self.widget)
        self.categoriestree.setGeometry(QtCore.QRect(0, 0, 251, 163))
        self.categoriestree.setObjectName(_fromUtf8("categoriestree"))
        self.categoriestree.headerItem().setText(0, _fromUtf8("1"))
        self.categoriestree.header().setVisible(False)
        self.toolBox.addItem(self.tb_categories, _fromUtf8(""))
        self.tb_tags = QtGui.QWidget()
        self.tb_tags.setGeometry(QtCore.QRect(0, 0, 205, 126))
        self.tb_tags.setObjectName(_fromUtf8("tb_tags"))
        self.widget_2 = QtGui.QWidget(self.tb_tags)
        self.widget_2.setGeometry(QtCore.QRect(-1, -1, 251, 181))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.tagsText = QtGui.QPlainTextEdit(self.widget_2)
        self.tagsText.setGeometry(QtCore.QRect(30, 0, 187, 297))
        self.tagsText.setObjectName(_fromUtf8("tagsText"))
        self.toolBox.addItem(self.tb_tags, _fromUtf8(""))
        self.tb_options = QtGui.QWidget()
        self.tb_options.setGeometry(QtCore.QRect(0, 0, 205, 126))
        self.tb_options.setObjectName(_fromUtf8("tb_options"))
        self.frame_2 = QtGui.QFrame(self.tb_options)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 241, 421))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout = QtGui.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.trackbackCheck = QtGui.QCheckBox(self.frame_2)
        self.trackbackCheck.setObjectName(_fromUtf8("trackbackCheck"))
        self.gridLayout.addWidget(self.trackbackCheck, 0, 1, 1, 1)
        self.commentsCheck = QtGui.QCheckBox(self.frame_2)
        self.commentsCheck.setObjectName(_fromUtf8("commentsCheck"))
        self.gridLayout.addWidget(self.commentsCheck, 1, 1, 1, 1)
        self.tagslabel = QtGui.QLabel(self.frame_2)
        self.tagslabel.setObjectName(_fromUtf8("tagslabel"))
        self.gridLayout.addWidget(self.tagslabel, 2, 0, 1, 1)
        self.toolBox.addItem(self.tb_options, _fromUtf8(""))
        self.tb_excerpt = QtGui.QWidget()
        self.tb_excerpt.setGeometry(QtCore.QRect(0, 0, 205, 126))
        self.tb_excerpt.setObjectName(_fromUtf8("tb_excerpt"))
        self.excerptText = QtGui.QPlainTextEdit(self.tb_excerpt)
        self.excerptText.setEnabled(True)
        self.excerptText.setGeometry(QtCore.QRect(30, -10, 164, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.excerptText.sizePolicy().hasHeightForWidth())
        self.excerptText.setSizePolicy(sizePolicy)
        self.excerptText.setObjectName(_fromUtf8("excerptText"))
        self.toolBox.addItem(self.tb_excerpt, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox)
        self.workarea = QtGui.QFrame(self.splitter)
        self.workarea.setMinimumSize(QtCore.QSize(613, 0))
        self.workarea.setFrameShape(QtGui.QFrame.NoFrame)
        self.workarea.setFrameShadow(QtGui.QFrame.Raised)
        self.workarea.setObjectName(_fromUtf8("workarea"))
        self.gridLayout_2 = QtGui.QGridLayout(self.workarea)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setHorizontalSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.posttitlelbl = QtGui.QLabel(self.workarea)
        self.posttitlelbl.setObjectName(_fromUtf8("posttitlelbl"))
        self.gridLayout_2.addWidget(self.posttitlelbl, 0, 0, 1, 1)
        self.posttitletxt = QtGui.QLineEdit(self.workarea)
        self.posttitletxt.setObjectName(_fromUtf8("posttitletxt"))
        self.gridLayout_2.addWidget(self.posttitletxt, 0, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.workarea)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Visual = QtGui.QWidget()
        self.Visual.setObjectName(_fromUtf8("Visual"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Visual)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.editView = QtWebKit.QWebView(self.Visual)
        self.editView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.editView.setObjectName(_fromUtf8("editView"))
        self.verticalLayout_2.addWidget(self.editView)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/visual.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Visual, icon1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_tab2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_tab2.setMargin(0)
        self.verticalLayout_tab2.setObjectName(_fromUtf8("verticalLayout_tab2"))
        self.codeView = QtWebKit.QWebView(self.tab_2)
        self.codeView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.codeView.setObjectName(_fromUtf8("codeView"))
        self.verticalLayout_tab2.addWidget(self.codeView)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/html.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_tab3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_tab3.setMargin(0)
        self.verticalLayout_tab3.setObjectName(_fromUtf8("verticalLayout_tab3"))
        self.preView = QtWebKit.QWebView(self.tab_3)
        self.preView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.preView.setObjectName(_fromUtf8("preView"))
        self.verticalLayout_tab3.addWidget(self.preView)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/preview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon3, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 2)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1219, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuB_log = QtGui.QMenu(self.menubar)
        self.menuB_log.setObjectName(_fromUtf8("menuB_log"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        MainWindow.setMenuBar(self.menubar)
        self.standardToolBar = QtGui.QToolBar(MainWindow)
        self.standardToolBar.setObjectName(_fromUtf8("standardToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.standardToolBar)
        self.actionFileNew = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileNew.setIcon(icon4)
        self.actionFileNew.setObjectName(_fromUtf8("actionFileNew"))
        self.actionFileOpen = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileOpen.setIcon(icon5)
        self.actionFileOpen.setObjectName(_fromUtf8("actionFileOpen"))
        self.actionFileSave = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileSave.setIcon(icon6)
        self.actionFileSave.setObjectName(_fromUtf8("actionFileSave"))
        self.actionFileSaveAs = QtGui.QAction(MainWindow)
        self.actionFileSaveAs.setObjectName(_fromUtf8("actionFileSaveAs"))
        self.actionZoomOut = QtGui.QAction(MainWindow)
        self.actionZoomOut.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon7)
        self.actionZoomOut.setObjectName(_fromUtf8("actionZoomOut"))
        self.actionZoomIn = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon8)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAddNewBlog = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/new_blog.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddNewBlog.setIcon(icon9)
        self.actionAddNewBlog.setObjectName(_fromUtf8("actionAddNewBlog"))
        self.actionEditManageBlogs = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/manage_blogs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditManageBlogs.setIcon(icon10)
        self.actionEditManageBlogs.setObjectName(_fromUtf8("actionEditManageBlogs"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionPublish = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/publishpost.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPublish.setIcon(icon11)
        self.actionPublish.setObjectName(_fromUtf8("actionPublish"))
        self.actionPublishAsDraft = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/publishdraft.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPublishAsDraft.setIcon(icon12)
        self.actionPublishAsDraft.setObjectName(_fromUtf8("actionPublishAsDraft"))
        self.menuB_log.addAction(self.actionEditManageBlogs)
        self.menuB_log.addAction(self.actionAddNewBlog)
        self.menuB_log.addAction(self.actionPublish)
        self.menuB_log.addAction(self.actionPublishAsDraft)
        self.menu_Edit.addAction(self.actionPreferences)
        self.menu_File.addAction(self.actionFileNew)
        self.menu_File.addAction(self.actionFileOpen)
        self.menu_File.addAction(self.actionFileSave)
        self.menu_File.addAction(self.actionFileSaveAs)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuB_log.menuAction())
        self.standardToolBar.addAction(self.actionFileNew)
        self.standardToolBar.addAction(self.actionFileOpen)
        self.standardToolBar.addAction(self.actionFileSave)
        self.standardToolBar.addSeparator()
        self.standardToolBar.addAction(self.actionAddNewBlog)
        self.standardToolBar.addAction(self.actionEditManageBlogs)
        self.standardToolBar.addAction(self.actionPublish)
        self.standardToolBar.addAction(self.actionPublishAsDraft)
        self.standardToolBar.addSeparator()
        self.standardToolBar.addAction(self.actionZoomIn)
        self.standardToolBar.addAction(self.actionZoomOut)

        self.retranslateUi(MainWindow)
        self.blogrel.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Rubrique", None, QtGui.QApplication.UnicodeUTF8))
        self.blogposts.setAccessibleName(QtGui.QApplication.translate("MainWindow", "Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.blogrel.setTabText(self.blogrel.indexOf(self.blogposts), QtGui.QApplication.translate("MainWindow", "Blog Posts", None, QtGui.QApplication.UnicodeUTF8))
        self.blogrel.setTabText(self.blogrel.indexOf(self.localposts), QtGui.QApplication.translate("MainWindow", "Local Posts", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tb_categories), QtGui.QApplication.translate("MainWindow", "Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tb_tags), QtGui.QApplication.translate("MainWindow", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.trackbackCheck.setText(QtGui.QApplication.translate("MainWindow", "Allow Trackbacks", None, QtGui.QApplication.UnicodeUTF8))
        self.commentsCheck.setText(QtGui.QApplication.translate("MainWindow", "Allow Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.tagslabel.setText(QtGui.QApplication.translate("MainWindow", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tb_options), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tb_excerpt), QtGui.QApplication.translate("MainWindow", "Excerpt", None, QtGui.QApplication.UnicodeUTF8))
        self.posttitlelbl.setText(QtGui.QApplication.translate("MainWindow", "Post Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Visual), QtGui.QApplication.translate("MainWindow", "Visual", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "HTML", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.menuB_log.setTitle(QtGui.QApplication.translate("MainWindow", "B&log", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.standardToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileNew.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddNewBlog.setText(QtGui.QApplication.translate("MainWindow", "Add New Blog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditManageBlogs.setText(QtGui.QApplication.translate("MainWindow", "Edit/Manage Blogs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPublish.setText(QtGui.QApplication.translate("MainWindow", "Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPublishAsDraft.setText(QtGui.QApplication.translate("MainWindow", "Publish As Draft", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import rubrique_rc
