# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_resources/rubrique.ui'
#
# Created: Tue Nov 22 19:44:27 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1223, 600)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/publishstamp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setEnabled(True)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(3)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.leftpane = QtGui.QFrame(self.splitter)
        self.leftpane.setMinimumSize(QtCore.QSize(150, 0))
        self.leftpane.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leftpane.setFrameShape(QtGui.QFrame.NoFrame)
        self.leftpane.setFrameShadow(QtGui.QFrame.Raised)
        self.leftpane.setLineWidth(0)
        self.leftpane.setObjectName(_fromUtf8("leftpane"))
        self.verticalLayout = QtGui.QVBoxLayout(self.leftpane)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setContentsMargins(3, 3, 0, 2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.blogrel = QtGui.QTabWidget(self.leftpane)
        self.blogrel.setTabPosition(QtGui.QTabWidget.North)
        self.blogrel.setTabShape(QtGui.QTabWidget.Rounded)
        self.blogrel.setObjectName(_fromUtf8("blogrel"))
        self.blogposts = QtGui.QWidget()
        self.blogposts.setObjectName(_fromUtf8("blogposts"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.blogposts)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.blogCombo = QtGui.QComboBox(self.blogposts)
        self.blogCombo.setObjectName(_fromUtf8("blogCombo"))
        self.verticalLayout_3.addWidget(self.blogCombo)
        self.postTree = QtGui.QTreeWidget(self.blogposts)
        self.postTree.setObjectName(_fromUtf8("postTree"))
        self.postTree.headerItem().setText(0, _fromUtf8("Posts"))
        self.postTree.header().setVisible(False)
        self.verticalLayout_3.addWidget(self.postTree)
        self.blogrel.addTab(self.blogposts, _fromUtf8(""))
        self.localpostsBgWidget = QtGui.QWidget()
        self.localpostsBgWidget.setObjectName(_fromUtf8("localpostsBgWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.localpostsBgWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.localpostsList = QtGui.QListWidget(self.localpostsBgWidget)
        self.localpostsList.setObjectName(_fromUtf8("localpostsList"))
        self.verticalLayout_4.addWidget(self.localpostsList)
        self.blogrel.addTab(self.localpostsBgWidget, _fromUtf8(""))
        self.verticalLayout.addWidget(self.blogrel)
        self.postBlogLabel = QtGui.QLabel(self.leftpane)
        self.postBlogLabel.setObjectName(_fromUtf8("postBlogLabel"))
        self.verticalLayout.addWidget(self.postBlogLabel)
        self.postBlogCombo = QtGui.QComboBox(self.leftpane)
        self.postBlogCombo.setObjectName(_fromUtf8("postBlogCombo"))
        self.verticalLayout.addWidget(self.postBlogCombo)
        self.toolBox = QtGui.QToolBox(self.leftpane)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.toolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Raised)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.tb_categories = QtGui.QWidget()
        self.tb_categories.setGeometry(QtCore.QRect(0, 0, 245, 142))
        self.tb_categories.setObjectName(_fromUtf8("tb_categories"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tb_categories)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QtGui.QWidget(self.tb_categories)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.categoriestree = QtGui.QTreeWidget(self.widget)
        self.categoriestree.setObjectName(_fromUtf8("categoriestree"))
        self.categoriestree.headerItem().setText(0, _fromUtf8("1"))
        self.categoriestree.header().setVisible(False)
        self.verticalLayout_6.addWidget(self.categoriestree)
        self.horizontalLayout.addWidget(self.widget)
        self.toolBox.addItem(self.tb_categories, _fromUtf8(""))
        self.tb_tags = QtGui.QWidget()
        self.tb_tags.setGeometry(QtCore.QRect(0, 0, 245, 142))
        self.tb_tags.setObjectName(_fromUtf8("tb_tags"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tb_tags)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.widget_2 = QtGui.QWidget(self.tb_tags)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tagsText = QtGui.QPlainTextEdit(self.widget_2)
        self.tagsText.setObjectName(_fromUtf8("tagsText"))
        self.verticalLayout_8.addWidget(self.tagsText)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.toolBox.addItem(self.tb_tags, _fromUtf8(""))
        self.tb_options = QtGui.QWidget()
        self.tb_options.setGeometry(QtCore.QRect(0, 0, 245, 85))
        self.tb_options.setObjectName(_fromUtf8("tb_options"))
        self.gridLayout = QtGui.QGridLayout(self.tb_options)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_2 = QtGui.QFrame(self.tb_options)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.trackbacksCheck = QtGui.QCheckBox(self.frame_2)
        self.trackbacksCheck.setObjectName(_fromUtf8("trackbacksCheck"))
        self.verticalLayout_5.addWidget(self.trackbacksCheck)
        self.commentsCheck = QtGui.QCheckBox(self.frame_2)
        self.commentsCheck.setObjectName(_fromUtf8("commentsCheck"))
        self.verticalLayout_5.addWidget(self.commentsCheck)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.toolBox.addItem(self.tb_options, _fromUtf8(""))
        self.tb_excerpt = QtGui.QWidget()
        self.tb_excerpt.setGeometry(QtCore.QRect(0, 0, 245, 142))
        self.tb_excerpt.setObjectName(_fromUtf8("tb_excerpt"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tb_excerpt)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.widget_3 = QtGui.QWidget(self.tb_excerpt)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.excerptTxt = QtGui.QPlainTextEdit(self.widget_3)
        self.excerptTxt.setObjectName(_fromUtf8("excerptTxt"))
        self.verticalLayout_10.addWidget(self.excerptTxt)
        self.verticalLayout_11.addWidget(self.widget_3)
        self.toolBox.addItem(self.tb_excerpt, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox)
        self.workarea = QtGui.QFrame(self.splitter)
        self.workarea.setMinimumSize(QtCore.QSize(613, 0))
        self.workarea.setFrameShape(QtGui.QFrame.NoFrame)
        self.workarea.setFrameShadow(QtGui.QFrame.Raised)
        self.workarea.setObjectName(_fromUtf8("workarea"))
        self.gridLayout_2 = QtGui.QGridLayout(self.workarea)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setHorizontalSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.postTitleLbl = QtGui.QLabel(self.workarea)
        self.postTitleLbl.setObjectName(_fromUtf8("postTitleLbl"))
        self.gridLayout_2.addWidget(self.postTitleLbl, 0, 0, 1, 1)
        self.postTitleTxt = QtGui.QLineEdit(self.workarea)
        self.postTitleTxt.setObjectName(_fromUtf8("postTitleTxt"))
        self.gridLayout_2.addWidget(self.postTitleTxt, 0, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.workarea)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Visual = QtGui.QWidget()
        self.Visual.setObjectName(_fromUtf8("Visual"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Visual)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.editView = QtGui.QTextEdit(self.Visual)
        self.editView.setObjectName(_fromUtf8("editView"))
        self.verticalLayout_2.addWidget(self.editView)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/visual.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Visual, icon1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_tab2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_tab2.setMargin(0)
        self.verticalLayout_tab2.setObjectName(_fromUtf8("verticalLayout_tab2"))
        self.codeView = Qsci.QsciScintilla(self.tab_2)
        self.codeView.setToolTip(_fromUtf8(""))
        self.codeView.setWhatsThis(_fromUtf8(""))
        self.codeView.setObjectName(_fromUtf8("codeView"))
        self.verticalLayout_tab2.addWidget(self.codeView)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/html.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_tab3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_tab3.setMargin(0)
        self.verticalLayout_tab3.setObjectName(_fromUtf8("verticalLayout_tab3"))
        self.preView = QtWebKit.QWebView(self.tab_3)
        self.preView.setProperty(_fromUtf8("url"), QtCore.QUrl(_fromUtf8("about:blank")))
        self.preView.setObjectName(_fromUtf8("preView"))
        self.verticalLayout_tab3.addWidget(self.preView)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/preview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(self.tab_4)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.testView = QtGui.QTextEdit(self.frame)
        self.testView.setObjectName(_fromUtf8("testView"))
        self.verticalLayout_12.addWidget(self.testView)
        self.horizontalLayout_2.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 2)
        self.verticalLayout_9.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1223, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuB_log = QtGui.QMenu(self.menubar)
        self.menuB_log.setObjectName(_fromUtf8("menuB_log"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuFormat = QtGui.QMenu(self.menubar)
        self.menuFormat.setObjectName(_fromUtf8("menuFormat"))
        self.menuAlign = QtGui.QMenu(self.menuFormat)
        self.menuAlign.setObjectName(_fromUtf8("menuAlign"))
        self.menuInsert = QtGui.QMenu(self.menubar)
        self.menuInsert.setObjectName(_fromUtf8("menuInsert"))
        self.menuTable = QtGui.QMenu(self.menubar)
        self.menuTable.setObjectName(_fromUtf8("menuTable"))
        self.menuInsert_Rows = QtGui.QMenu(self.menuTable)
        self.menuInsert_Rows.setObjectName(_fromUtf8("menuInsert_Rows"))
        self.menuInsert_Columns = QtGui.QMenu(self.menuTable)
        self.menuInsert_Columns.setObjectName(_fromUtf8("menuInsert_Columns"))
        self.menuTest = QtGui.QMenu(self.menubar)
        self.menuTest.setObjectName(_fromUtf8("menuTest"))
        MainWindow.setMenuBar(self.menubar)
        self.standardToolBar = QtGui.QToolBar(MainWindow)
        self.standardToolBar.setIconSize(QtCore.QSize(24, 24))
        self.standardToolBar.setObjectName(_fromUtf8("standardToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.standardToolBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.actionFileNew = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileNew.setIcon(icon4)
        self.actionFileNew.setObjectName(_fromUtf8("actionFileNew"))
        self.actionFileOpen = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileOpen.setIcon(icon5)
        self.actionFileOpen.setObjectName(_fromUtf8("actionFileOpen"))
        self.actionFileSave = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileSave.setIcon(icon6)
        self.actionFileSave.setObjectName(_fromUtf8("actionFileSave"))
        self.actionFileSaveAs = QtGui.QAction(MainWindow)
        self.actionFileSaveAs.setObjectName(_fromUtf8("actionFileSaveAs"))
        self.actionZoomOut = QtGui.QAction(MainWindow)
        self.actionZoomOut.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon7)
        self.actionZoomOut.setObjectName(_fromUtf8("actionZoomOut"))
        self.actionZoomIn = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon8)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAddNewBlog = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/new_blog.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddNewBlog.setIcon(icon9)
        self.actionAddNewBlog.setObjectName(_fromUtf8("actionAddNewBlog"))
        self.actionEditManageBlogs = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/manage_blogs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditManageBlogs.setIcon(icon10)
        self.actionEditManageBlogs.setObjectName(_fromUtf8("actionEditManageBlogs"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionPublish = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/publishpost.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPublish.setIcon(icon11)
        self.actionPublish.setObjectName(_fromUtf8("actionPublish"))
        self.actionPublishAsDraft = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/myimages/publishdraft.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPublishAsDraft.setIcon(icon12)
        self.actionPublishAsDraft.setObjectName(_fromUtf8("actionPublishAsDraft"))
        self.actionChoose_Blog = QtGui.QAction(MainWindow)
        self.actionChoose_Blog.setObjectName(_fromUtf8("actionChoose_Blog"))
        self.actionBold = QtGui.QAction(MainWindow)
        self.actionBold.setCheckable(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/bold.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBold.setIcon(icon13)
        self.actionBold.setObjectName(_fromUtf8("actionBold"))
        self.actionItalics = QtGui.QAction(MainWindow)
        self.actionItalics.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/italic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalics.setIcon(icon14)
        self.actionItalics.setObjectName(_fromUtf8("actionItalics"))
        self.actionLeft = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/align_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLeft.setIcon(icon15)
        self.actionLeft.setObjectName(_fromUtf8("actionLeft"))
        self.actionRight = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/align_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRight.setIcon(icon16)
        self.actionRight.setObjectName(_fromUtf8("actionRight"))
        self.actionCenter = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/align_center.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCenter.setIcon(icon17)
        self.actionCenter.setObjectName(_fromUtf8("actionCenter"))
        self.actionJustify = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/align_justify.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJustify.setIcon(icon18)
        self.actionJustify.setObjectName(_fromUtf8("actionJustify"))
        self.actionInsert_Image = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/insert_image.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsert_Image.setIcon(icon19)
        self.actionInsert_Image.setObjectName(_fromUtf8("actionInsert_Image"))
        self.actionAdd_Link = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/insert_link.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Link.setIcon(icon20)
        self.actionAdd_Link.setObjectName(_fromUtf8("actionAdd_Link"))
        self.actionInsert_Video = QtGui.QAction(MainWindow)
        self.actionInsert_Video.setObjectName(_fromUtf8("actionInsert_Video"))
        self.actionTable = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTable.setIcon(icon21)
        self.actionTable.setObjectName(_fromUtf8("actionTable"))
        self.actionUnderline = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/underline.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnderline.setIcon(icon22)
        self.actionUnderline.setObjectName(_fromUtf8("actionUnderline"))
        self.actionFormat_Table = QtGui.QAction(MainWindow)
        self.actionFormat_Table.setObjectName(_fromUtf8("actionFormat_Table"))
        self.actionDelete_Columns = QtGui.QAction(MainWindow)
        self.actionDelete_Columns.setObjectName(_fromUtf8("actionDelete_Columns"))
        self.actionSet_Column_Width = QtGui.QAction(MainWindow)
        self.actionSet_Column_Width.setObjectName(_fromUtf8("actionSet_Column_Width"))
        self.actionDelete_Rows = QtGui.QAction(MainWindow)
        self.actionDelete_Rows.setObjectName(_fromUtf8("actionDelete_Rows"))
        self.actionMerge_Selected_Cells = QtGui.QAction(MainWindow)
        self.actionMerge_Selected_Cells.setObjectName(_fromUtf8("actionMerge_Selected_Cells"))
        self.actionCell_Background_Colour = QtGui.QAction(MainWindow)
        self.actionCell_Background_Colour.setObjectName(_fromUtf8("actionCell_Background_Colour"))
        self.actionBeforeRow = QtGui.QAction(MainWindow)
        self.actionBeforeRow.setObjectName(_fromUtf8("actionBeforeRow"))
        self.actionAfterRow = QtGui.QAction(MainWindow)
        self.actionAfterRow.setObjectName(_fromUtf8("actionAfterRow"))
        self.actionBeforeColumn = QtGui.QAction(MainWindow)
        self.actionBeforeColumn.setObjectName(_fromUtf8("actionBeforeColumn"))
        self.actionAfterColumn = QtGui.QAction(MainWindow)
        self.actionAfterColumn.setObjectName(_fromUtf8("actionAfterColumn"))
        self.actionSplit_Cell = QtGui.QAction(MainWindow)
        self.actionSplit_Cell.setObjectName(_fromUtf8("actionSplit_Cell"))
        self.actionUndo = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon23)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/wysiwyg/redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon24)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionUndo_2 = QtGui.QAction(MainWindow)
        self.actionUndo_2.setObjectName(_fromUtf8("actionUndo_2"))
        self.actionRedo_2 = QtGui.QAction(MainWindow)
        self.actionRedo_2.setObjectName(_fromUtf8("actionRedo_2"))
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.menuB_log.addAction(self.actionEditManageBlogs)
        self.menuB_log.addAction(self.actionAddNewBlog)
        self.menuB_log.addAction(self.actionPublish)
        self.menuB_log.addAction(self.actionPublishAsDraft)
        self.menu_Edit.addAction(self.actionPreferences)
        self.menu_Edit.addAction(self.actionUndo)
        self.menu_Edit.addAction(self.actionRedo)
        self.menu_File.addAction(self.actionFileNew)
        self.menu_File.addAction(self.actionFileOpen)
        self.menu_File.addAction(self.actionFileSave)
        self.menu_File.addAction(self.actionFileSaveAs)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menuAlign.addAction(self.actionLeft)
        self.menuAlign.addAction(self.actionRight)
        self.menuAlign.addAction(self.actionCenter)
        self.menuAlign.addAction(self.actionJustify)
        self.menuFormat.addAction(self.actionBold)
        self.menuFormat.addAction(self.actionItalics)
        self.menuFormat.addAction(self.actionUnderline)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.menuAlign.menuAction())
        self.menuFormat.addSeparator()
        self.menuInsert.addAction(self.actionInsert_Image)
        self.menuInsert.addAction(self.actionAdd_Link)
        self.menuInsert.addAction(self.actionInsert_Video)
        self.menuInsert.addAction(self.actionTable)
        self.menuInsert_Rows.addAction(self.actionBeforeRow)
        self.menuInsert_Rows.addAction(self.actionAfterRow)
        self.menuInsert_Columns.addAction(self.actionBeforeColumn)
        self.menuInsert_Columns.addAction(self.actionAfterColumn)
        self.menuTable.addAction(self.actionTable)
        self.menuTable.addAction(self.actionFormat_Table)
        self.menuTable.addAction(self.menuInsert_Rows.menuAction())
        self.menuTable.addAction(self.menuInsert_Columns.menuAction())
        self.menuTable.addAction(self.actionDelete_Rows)
        self.menuTable.addAction(self.actionDelete_Columns)
        self.menuTable.addAction(self.actionSet_Column_Width)
        self.menuTable.addAction(self.actionMerge_Selected_Cells)
        self.menuTable.addAction(self.actionSplit_Cell)
        self.menuTable.addAction(self.actionCell_Background_Colour)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionUndo_2)
        self.menuTest.addAction(self.actionRedo_2)
        self.menuTest.addAction(self.actionClear)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuB_log.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.menubar.addAction(self.menuInsert.menuAction())
        self.menubar.addAction(self.menuTable.menuAction())
        self.menubar.addAction(self.menuTest.menuAction())
        self.standardToolBar.addAction(self.actionFileNew)
        self.standardToolBar.addAction(self.actionFileSave)
        self.standardToolBar.addSeparator()
        self.standardToolBar.addAction(self.actionAddNewBlog)
        self.standardToolBar.addAction(self.actionEditManageBlogs)
        self.standardToolBar.addAction(self.actionPublish)
        self.standardToolBar.addAction(self.actionPublishAsDraft)
        self.standardToolBar.addSeparator()
        self.standardToolBar.addSeparator()
        self.toolBar.addAction(self.actionBold)
        self.toolBar.addAction(self.actionItalics)
        self.toolBar.addAction(self.actionUnderline)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLeft)
        self.toolBar.addAction(self.actionCenter)
        self.toolBar.addAction(self.actionJustify)
        self.toolBar.addAction(self.actionRight)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionInsert_Image)
        self.toolBar.addAction(self.actionAdd_Link)
        self.toolBar.addAction(self.actionInsert_Video)
        self.toolBar.addAction(self.actionTable)

        self.retranslateUi(MainWindow)
        self.blogrel.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Rubrique", None, QtGui.QApplication.UnicodeUTF8))
        self.blogposts.setAccessibleName(QtGui.QApplication.translate("MainWindow", "Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.blogrel.setTabText(self.blogrel.indexOf(self.blogposts), QtGui.QApplication.translate("MainWindow", "Blog Posts", None, QtGui.QApplication.UnicodeUTF8))
        self.blogrel.setTabText(self.blogrel.indexOf(self.localpostsBgWidget), QtGui.QApplication.translate("MainWindow", "Local Posts", None, QtGui.QApplication.UnicodeUTF8))
        self.postBlogLabel.setText(QtGui.QApplication.translate("MainWindow", "Post Belongs to:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tb_categories), QtGui.QApplication.translate("MainWindow", "Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tb_tags), QtGui.QApplication.translate("MainWindow", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.trackbacksCheck.setText(QtGui.QApplication.translate("MainWindow", "Allow Trackbacks", None, QtGui.QApplication.UnicodeUTF8))
        self.commentsCheck.setText(QtGui.QApplication.translate("MainWindow", "Allow Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tb_options), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tb_excerpt), QtGui.QApplication.translate("MainWindow", "Excerpt", None, QtGui.QApplication.UnicodeUTF8))
        self.postTitleLbl.setText(QtGui.QApplication.translate("MainWindow", "Post Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Visual), QtGui.QApplication.translate("MainWindow", "Visual", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "HTML", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.menuB_log.setTitle(QtGui.QApplication.translate("MainWindow", "B&log", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFormat.setTitle(QtGui.QApplication.translate("MainWindow", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAlign.setTitle(QtGui.QApplication.translate("MainWindow", "Align", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInsert.setTitle(QtGui.QApplication.translate("MainWindow", "Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTable.setTitle(QtGui.QApplication.translate("MainWindow", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInsert_Rows.setTitle(QtGui.QApplication.translate("MainWindow", "Insert Rows", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInsert_Columns.setTitle(QtGui.QApplication.translate("MainWindow", "Insert Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTest.setTitle(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.standardToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileNew.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddNewBlog.setText(QtGui.QApplication.translate("MainWindow", "Add New Blog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditManageBlogs.setText(QtGui.QApplication.translate("MainWindow", "Edit/Manage Blogs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPublish.setText(QtGui.QApplication.translate("MainWindow", "Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPublishAsDraft.setText(QtGui.QApplication.translate("MainWindow", "Publish As Draft", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChoose_Blog.setText(QtGui.QApplication.translate("MainWindow", "Choose Current Blog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBold.setText(QtGui.QApplication.translate("MainWindow", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBold.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionItalics.setText(QtGui.QApplication.translate("MainWindow", "Italics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionItalics.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLeft.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLeft.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRight.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRight.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCenter.setText(QtGui.QApplication.translate("MainWindow", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCenter.setToolTip(QtGui.QApplication.translate("MainWindow", "Center ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCenter.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJustify.setText(QtGui.QApplication.translate("MainWindow", "Justify", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJustify.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+J", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsert_Image.setText(QtGui.QApplication.translate("MainWindow", "Insert Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Link.setText(QtGui.QApplication.translate("MainWindow", "Link", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Link.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsert_Video.setText(QtGui.QApplication.translate("MainWindow", "Video", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTable.setText(QtGui.QApplication.translate("MainWindow", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnderline.setText(QtGui.QApplication.translate("MainWindow", "Underline", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnderline.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFormat_Table.setText(QtGui.QApplication.translate("MainWindow", "Format Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Columns.setText(QtGui.QApplication.translate("MainWindow", "Delete Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Column_Width.setText(QtGui.QApplication.translate("MainWindow", "Set Column Width", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Rows.setText(QtGui.QApplication.translate("MainWindow", "Delete Rows", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMerge_Selected_Cells.setText(QtGui.QApplication.translate("MainWindow", "Merge Selected Cells", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCell_Background_Colour.setText(QtGui.QApplication.translate("MainWindow", "Cell Background Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeforeRow.setText(QtGui.QApplication.translate("MainWindow", "Before", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAfterRow.setText(QtGui.QApplication.translate("MainWindow", "After", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeforeColumn.setText(QtGui.QApplication.translate("MainWindow", "Before", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAfterColumn.setText(QtGui.QApplication.translate("MainWindow", "After", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSplit_Cell.setText(QtGui.QApplication.translate("MainWindow", "Split Cell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo_2.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo_2.setText(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qsci
from PyQt4 import QtWebKit
import rubrique_rc
import wysiwyg_rc
